
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: dcs_postgis_db
    restart: always
    environment:
      POSTGRES_DB: DCS
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: kevin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kevin -d DCS"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: dcs_sdjango_app
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: DCS
      DB_USER: kevin
      DB_PASSWORD: kevin
      DB_PORT: 5432

volumes:
  postgres_data:
